package com.SVRPlatform.model;

// Generated 2012-11-24 21:57:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bug generated by hbm2java
 */
public class Bug implements java.io.Serializable {

	private Integer bugId;
	private String version;
	private Software software;
	private User user;
	private Integer level;
	private String graphAddress;
	private Date datetime;
	private String description;
	private Integer bestSolutionId;
	private Integer officialSolutionId;
	private String bugDigest;
	private Byte usabilityImpact;
	private Byte dataImpact;
	private Byte privacyImpact;
	private Byte availabilityImpact;
	private Byte frequency;
	private Byte score;
	private String language;
	private String bugNumber;
	private Set rankings = new HashSet(0);
	private Set solutions = new HashSet(0);
	private Set<User> users = new HashSet<User>(0);
	private Set comments = new HashSet(0);

	public Bug() {
	}

	public Bug(Software software, User user, Integer level,
			String graphAddress, Date datetime, String description,
			Integer bestSolutionId, Integer officialSolutionId,
			String bugDigest, Byte usabilityImpact, Byte dataImpact,
			Byte privacyImpact, Byte availabilityImpact, Byte frequency,
			Byte score, String language, String bugNumber, Set rankings,
			Set solutions, Set users, Set comments) {
		this.software = software;
		this.user = user;
		this.level = level;
		this.graphAddress = graphAddress;
		this.datetime = datetime;
		this.description = description;
		this.bestSolutionId = bestSolutionId;
		this.officialSolutionId = officialSolutionId;
		this.bugDigest = bugDigest;
		this.usabilityImpact = usabilityImpact;
		this.dataImpact = dataImpact;
		this.privacyImpact = privacyImpact;
		this.availabilityImpact = availabilityImpact;
		this.frequency = frequency;
		this.score = score;
		this.language = language;
		this.bugNumber = bugNumber;
		this.rankings = rankings;
		this.solutions = solutions;
		this.users = users;
		this.comments = comments;
	}

	public Integer getBugId() {
		return this.bugId;
	}

	public void setBugId(Integer bugId) {
		this.bugId = bugId;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Software getSoftware() {
		return this.software;
	}

	public void setSoftware(Software software) {
		this.software = software;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getGraphAddress() {
		return this.graphAddress;
	}

	public void setGraphAddress(String graphAddress) {
		this.graphAddress = graphAddress;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getBestSolutionId() {
		return this.bestSolutionId;
	}

	public void setBestSolutionId(Integer bestSolutionId) {
		this.bestSolutionId = bestSolutionId;
	}

	public Integer getOfficialSolutionId() {
		return this.officialSolutionId;
	}

	public void setOfficialSolutionId(Integer officialSolutionId) {
		this.officialSolutionId = officialSolutionId;
	}

	public String getBugDigest() {
		return this.bugDigest;
	}

	public void setBugDigest(String bugDigest) {
		this.bugDigest = bugDigest;
	}

	public Byte getUsabilityImpact() {
		return this.usabilityImpact;
	}

	public void setUsabilityImpact(Byte usabilityImpact) {
		this.usabilityImpact = usabilityImpact;
	}

	public Byte getDataImpact() {
		return this.dataImpact;
	}

	public void setDataImpact(Byte dataImpact) {
		this.dataImpact = dataImpact;
	}

	public Byte getPrivacyImpact() {
		return this.privacyImpact;
	}

	public void setPrivacyImpact(Byte privacyImpact) {
		this.privacyImpact = privacyImpact;
	}

	public Byte getAvailabilityImpact() {
		return this.availabilityImpact;
	}

	public void setAvailabilityImpact(Byte availabilityImpact) {
		this.availabilityImpact = availabilityImpact;
	}

	public Byte getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Byte frequency) {
		this.frequency = frequency;
	}

	public Byte getScore() {
		return this.score;
	}

	public void setScore(Byte score) {
		this.score = score;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getBugNumber() {
		return this.bugNumber;
	}

	public void setBugNumber(String bugNumber) {
		this.bugNumber = bugNumber;
	}

	public Set getRankings() {
		return this.rankings;
	}

	public void setRankings(Set rankings) {
		this.rankings = rankings;
	}

	public Set getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set solutions) {
		this.solutions = solutions;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
