package com.SVRPlatform.model;

// Generated 2012-11-24 21:57:04 by Hibernate Tools 3.4.0.CR1

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private CommentId id;
	private User user;
	private Bug bug;

	public Comment() {
	}

	public Comment(CommentId id) {
		this.id = id;
	}

	public Comment(CommentId id, User user, Bug bug) {
		this.id = id;
		this.user = user;
		this.bug = bug;
	}

	public CommentId getId() {
		return this.id;
	}

	public void setId(CommentId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

}
