package com.SVRPlatform.model;

// Generated 2012-11-24 21:57:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CommentId generated by hbm2java
 */
public class CommentId implements java.io.Serializable {

	private Integer bugId;
	private Integer userId;
	private Date datetime;
	private String content;
	private String commentTitle;

	public CommentId() {
	}

	public CommentId(Integer bugId, Integer userId, Date datetime,
			String content, String commentTitle) {
		this.bugId = bugId;
		this.userId = userId;
		this.datetime = datetime;
		this.content = content;
		this.commentTitle = commentTitle;
	}

	public Integer getBugId() {
		return this.bugId;
	}

	public void setBugId(Integer bugId) {
		this.bugId = bugId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCommentTitle() {
		return this.commentTitle;
	}

	public void setCommentTitle(String commentTitle) {
		this.commentTitle = commentTitle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentId))
			return false;
		CommentId castOther = (CommentId) other;

		return ((this.getBugId() == castOther.getBugId()) || (this.getBugId() != null
				&& castOther.getBugId() != null && this.getBugId().equals(
				castOther.getBugId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getDatetime() == castOther.getDatetime()) || (this
						.getDatetime() != null
						&& castOther.getDatetime() != null && this
						.getDatetime().equals(castOther.getDatetime())))
				&& ((this.getContent() == castOther.getContent()) || (this
						.getContent() != null && castOther.getContent() != null && this
						.getContent().equals(castOther.getContent())))
				&& ((this.getCommentTitle() == castOther.getCommentTitle()) || (this
						.getCommentTitle() != null
						&& castOther.getCommentTitle() != null && this
						.getCommentTitle().equals(castOther.getCommentTitle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBugId() == null ? 0 : this.getBugId().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getDatetime() == null ? 0 : this.getDatetime().hashCode());
		result = 37 * result
				+ (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37
				* result
				+ (getCommentTitle() == null ? 0 : this.getCommentTitle()
						.hashCode());
		return result;
	}

}
