package com.SVRPlatform.model;

// Generated 2012-11-30 16:34:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment extends BasicCommentAndSolution implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer commentId;
	private Date datetime;
	private String content;
	private String commentTitle;

	public Comment() {
	}

	public Comment(User user, Bug bug, Date datetime, String content,
			String commentTitle) {
		this.user = user;
		this.bug = bug;
		this.datetime = datetime;
		this.content = content;
		this.commentTitle = commentTitle;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCommentTitle() {
		return this.commentTitle;
	}

	public void setCommentTitle(String commentTitle) {
		this.commentTitle = commentTitle;
	}

}
