package com.SVRPlatform.model;

// Generated 2012-11-30 16:34:58 by Hibernate Tools 3.4.0.CR1

/**
 * Ranking generated by hbm2java
 */
public class Ranking implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int bugId;
	private Bug bug;

	public Ranking() {
	}

	public Ranking(Bug bug) {
		this.bug = bug;
	}

	public int getBugId() {
		return this.bugId;
	}

	public void setBugId(int bugId) {
		this.bugId = bugId;
	}

	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

}
