package com.SVRPlatform.model;

// Generated 2012-11-30 16:34:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Software generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Software implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer softwareId;
	private String company;
	private String name;
	private String productType;
	private Set bugs = new HashSet(0);

	public Software() {
	}

	public Software(String company, String name, String productType, Set bugs) {
		this.company = company;
		this.name = name;
		this.productType = productType;
		this.bugs = bugs;
	}

	public Integer getSoftwareId() {
		return this.softwareId;
	}

	public void setSoftwareId(Integer softwareId) {
		this.softwareId = softwareId;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public Set getBugs() {
		return this.bugs;
	}

	public void setBugs(Set bugs) {
		this.bugs = bugs;
	}

}
