package com.SVRPlatform.model;

// Generated 2012-11-24 21:57:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Solution generated by hbm2java
 */
public class Solution implements java.io.Serializable {

	private Integer solutionId;
	private User user;
	private Bug bug;
	private Date datetime;
	private String content;
	private Integer up;
	private Integer down;

	public Solution() {
	}

	public Solution(User user, Bug bug, Date datetime, String content,
			Integer up, Integer down) {
		this.user = user;
		this.bug = bug;
		this.datetime = datetime;
		this.content = content;
		this.up = up;
		this.down = down;
	}

	public Integer getSolutionId() {
		return this.solutionId;
	}

	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getUp() {
		return this.up;
	}

	public void setUp(Integer up) {
		this.up = up;
	}

	public Integer getDown() {
		return this.down;
	}

	public void setDown(Integer down) {
		this.down = down;
	}

}
