package com.SVRPlatform.model;

// Generated 2012-11-24 21:57:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String password;
	private String email;
	private Date date;
	private Integer credit;
	private String realName;
	private String website;
	private String location;
	private Integer age;
	private Date seen;
	private Integer profileViews;
	private Set solutions = new HashSet(0);
	private Set bugs = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set usertypes = new HashSet(0);
	private Set bugs_1 = new HashSet(0);

	public User() {
	}

	public User(String password, String email) {
		this.password = password;
		this.email = email;
	}

	public User(String password, String email, Date date, Integer credit,
			String realName, String website, String location, Integer age,
			Date seen, Integer profileViews, Set solutions, Set bugs,
			Set comments, Set usertypes, Set bugs_1) {
		this.password = password;
		this.email = email;
		this.date = date;
		this.credit = credit;
		this.realName = realName;
		this.website = website;
		this.location = location;
		this.age = age;
		this.seen = seen;
		this.profileViews = profileViews;
		this.solutions = solutions;
		this.bugs = bugs;
		this.comments = comments;
		this.usertypes = usertypes;
		this.bugs_1 = bugs_1;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getSeen() {
		return this.seen;
	}

	public void setSeen(Date seen) {
		this.seen = seen;
	}

	public Integer getProfileViews() {
		return this.profileViews;
	}

	public void setProfileViews(Integer profileViews) {
		this.profileViews = profileViews;
	}

	public Set getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set solutions) {
		this.solutions = solutions;
	}

	public Set getBugs() {
		return this.bugs;
	}

	public void setBugs(Set bugs) {
		this.bugs = bugs;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getUsertypes() {
		return this.usertypes;
	}

	public void setUsertypes(Set usertypes) {
		this.usertypes = usertypes;
	}

	public Set getBugs_1() {
		return this.bugs_1;
	}

	public void setBugs_1(Set bugs_1) {
		this.bugs_1 = bugs_1;
	}

}
