package com.SVRPlatform.model;

// Generated 2012-11-24 21:57:04 by Hibernate Tools 3.4.0.CR1

/**
 * Usertype generated by hbm2java
 */
public class Usertype implements java.io.Serializable {

	private int userId;
	private User user;
	private Integer usertype;

	public Usertype() {
	}

	public Usertype(int userId, User user) {
		this.userId = userId;
		this.user = user;
	}

	public Usertype(int userId, User user, Integer usertype) {
		this.userId = userId;
		this.user = user;
		this.usertype = usertype;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Integer usertype) {
		this.usertype = usertype;
	}

}
