package com.SVRPlatform.model;

// Generated 2012-11-30 16:34:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String password;
	private String email;
	private Date date;
	private Integer credit;
	private String realName;
	private String website;
	private String location;
	private Integer age;
	private Date seen;
	private Integer profileViews;
//	private Set solutions = new HashSet(0);
//	private Set hasBugs = new HashSet(0);
//	private Set comments = new HashSet(0);
	private Usertype usertype;
//	private Set watchingBugs = new HashSet(0);
	
	private String cookieHash;
	private Date validDeadline;

	public User() {
	}

	public User(String password, String email) {
		this.password = password;
		this.email = email;
	}

	public User(String password, String email, Date date, Integer credit,
			String realName, String website, String location, Integer age,
			Date seen, Integer profileViews, Set solutions, Set bugs,
			Set comments, Usertype usertype, Set watchingBugs) {
		this.password = password;
		this.email = email;
		this.date = date;
		this.credit = credit;
		this.realName = realName;
		this.website = website;
		this.location = location;
		this.age = age;
		this.seen = seen;
		this.profileViews = profileViews;
//		this.solutions = solutions;
//		this.hasBugs = bugs;
//		this.comments = comments;
		this.usertype = usertype;
//		this.watchingBugs = watchingBugs;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getSeen() {
		return this.seen;
	}

	public void setSeen(Date seen) {
		this.seen = seen;
	}

	public Integer getProfileViews() {
		return this.profileViews;
	}

	public void setProfileViews(Integer profileViews) {
		this.profileViews = profileViews;
	}

//	public Set getSolutions() {
//		return this.solutions;
//	}
//
//	public void setSolutions(Set solutions) {
//		this.solutions = solutions;
//	}
//
//	public Set getHasBugs() {
//		return this.hasBugs;
//	}
//
//	public void setHasBugs(Set hasBugs) {
//		this.hasBugs = hasBugs;
//	}
//
//	public Set getComments() {
//		return this.comments;
//	}
//
//	public void setComments(Set comments) {
//		this.comments = comments;
//	}

	public Usertype getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Usertype usertype) {
		this.usertype = usertype;
	}

//	public Set getWatchingBugs() {
//		return this.watchingBugs;
//	}
//
//	public void setWatchingBugs(Set watchingBugs) {
//		this.watchingBugs = watchingBugs;
//	}

	public String getCookieHash() {
		return cookieHash;
	}

	public void setCookieHash(String cookieHash) {
		this.cookieHash = cookieHash;
	}

	public Date getValidDeadline() {
		return validDeadline;
	}

	public void setValidDeadline(Date validDeadline) {
		this.validDeadline = validDeadline;
	}

}
