package com.SVRPlatform.model;

// Generated 2012-11-23 17:09:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5950945429102132924L;
	private Integer userId;
	private String password;
	private String email;
	private Date date;
	private Integer point;

	public Users() {
	}

	public Users(String password, String email) {
		this.password = password;
		this.email = email;
	}

	public Users(String password, String email, Date date, Integer point) {
		this.password = password;
		this.email = email;
		this.date = date;
		this.point = point;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

}
